# Use an official Python runtime as a parent image
FROM python:3.12-slim

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Set work directory
WORKDIR /app

apt install postgresql postgresql-contrib

# Install Python dependencies
COPY requirements.txt /app/
RUN pip install --no-cache-dir -U wheel pip
RUN pip install --no-cache-dir -r requirements.txt

# Copy project
COPY . /app/
