# Generated by Django 6.0.4 on 2026-04-09 15:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("ip_address", models.GenericIPAddressField()),
                ("vendor", models.CharField(max_length=100)),
                ("napalm_driver", models.CharField(max_length=100)),
                ("username", models.CharField(max_length=255)),
                ("password", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
