# Generated by Django 6.0.4 on 2026-04-18 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="progress",
            field=models.IntegerField(default=0),
        ),
    ]
